export const HeroRating = () => {
  return (
    <div className="text-gray-600 text-[13.12px] items-center box-border caret-transparent gap-x-3 flex flex-wrap leading-[20.992px] gap-y-[6.4px] mt-[6.4px] md:text-[13.76px] md:leading-[22.016px]">
      <div className="text-amber-500 text-[13.12px] items-center box-border caret-transparent gap-x-[2.4px] flex leading-[20.992px] gap-y-[2.4px] md:text-[13.76px] md:leading-[22.016px]">
        <i className="text-[14.4px] font-black box-border caret-transparent block leading-[14.4px] font-font_awesome_6_free before:accent-auto before:box-border before:caret-transparent before:text-amber-500 before:text-[14.4px] before:not-italic before:normal-nums before:font-black before:tracking-[normal] before:leading-[14.4px] before:list-outside before:list-disc before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-font_awesome_6_free"></i>
        <i className="text-[14.4px] font-black box-border caret-transparent block leading-[14.4px] font-font_awesome_6_free before:accent-auto before:box-border before:caret-transparent before:text-amber-500 before:text-[14.4px] before:not-italic before:normal-nums before:font-black before:tracking-[normal] before:leading-[14.4px] before:list-outside before:list-disc before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-font_awesome_6_free"></i>
        <i className="text-[14.4px] font-black box-border caret-transparent block leading-[14.4px] font-font_awesome_6_free before:accent-auto before:box-border before:caret-transparent before:text-amber-500 before:text-[14.4px] before:not-italic before:normal-nums before:font-black before:tracking-[normal] before:leading-[14.4px] before:list-outside before:list-disc before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-font_awesome_6_free"></i>
        <i className="text-[14.4px] font-black box-border caret-transparent block leading-[14.4px] font-font_awesome_6_free before:accent-auto before:box-border before:caret-transparent before:text-amber-500 before:text-[14.4px] before:not-italic before:normal-nums before:font-black before:tracking-[normal] before:leading-[14.4px] before:list-outside before:list-disc before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-font_awesome_6_free"></i>
        <i className="text-[14.4px] font-black box-border caret-transparent block leading-[14.4px] font-font_awesome_6_free before:accent-auto before:box-border before:caret-transparent before:text-amber-500 before:text-[14.4px] before:not-italic before:normal-nums before:font-black before:tracking-[normal] before:leading-[14.4px] before:list-outside before:list-disc before:pointer-events-auto before:text-start before:indent-[0px] before:normal-case before:visible before:border-separate before:font-font_awesome_6_free"></i>
      </div>
      <span className="text-[13.12px] box-border caret-transparent block leading-[20.992px] md:text-[13.76px] md:leading-[22.016px]">
        4.8 / 5 average satisfaction from business owners
      </span>
    </div>
  );
};
